### ISSUE TITLE
ComposeWindow is shown before the first frame is rendered

### ISSUE THREAD

**Issue by elijah-semyonov** [JetBrains/compose-multiplatform#3492]
**Describe the bug**
White flickering when presenting/pushing ComposeWindow

**Affected platforms**
- iOS
- Other

**Versions**
Latest master

https://github.com/JetBrains/compose-multiplatform/assets/4167681/36b5edeb-e7a8-4274-adc4-357625b2555c

## Meta
Reported by [Guilherme Delgado](https://kotlinlang.slack.com/team/U01SRV4CQKF)

**Comment by gastsail** [comment]
Hmm, could have to do with the navigation lib you are using?

**Comment by GuilhE** [comment]
> Hmm, could have to do with the navigation lib you are using?

I don't think so, navigation is being made with NavigationStack on iOS side (no 3rd party).

**Comment by elijah-semyonov** [comment]
We will add explicit wait for the first rendered frame to avoid this. I'll link related PR when it's done.

**Comment by elijah-semyonov** [comment]
Fixed in [PR](https://github.com/JetBrains/compose-multiplatform-core/pull/766)

**Comment by GuilhE** [comment]
@elijah-semyonov not deployed yet right?

**Comment by elijah-semyonov** [comment]
No, will be in next minor version

**Comment by chrisbanes** [comment]
FYI, still seeing this in 1.5.1. Can we add an option to set the background color? 

I don't think you'll ever be ever to guarantee that Compose goes through a whole draw pass before iOS does.

**Comment by GuilhE** [comment]
Yup tested again with:

```
gradleComposeMultiplatform = "1.5.1"
composeMultiplatformCompiler = "1.5.2-beta01"
```
And I can still see the white background.

**Comment by elijah-semyonov** [comment]
@GuilhE 
Could you please provide a repro? I agree with @chrisbanes that we can't guarantee that Compose goes through whole draw pass before iOS does, but I'm interested in particular chain of events, that bypass the fix.

**Comment by GuilhE** [comment]
> @GuilhE Could you please provide a repro? I agree with @chrisbanes that we can't guarantee that Compose goes through whole draw pass before iOS does, but I'm interested in particular chain of events, that bypass the fix.

Yes of course, check it here https://github.com/GuilhE/Expressus

**Comment by elijah-semyonov** [comment]
My bad, the fix is not live yet. Will be there in 1.5.10.

**Comment by GuilhE** [comment]
I can confirm that `1.5.10-beta01` fixes this problem

**Comment by chokokatana** [comment]
I'm hitting this problem avoiding SwiftUI using normal UIViewController classes. I even tried to force the background of the views to black before pushing them with pseudo code like this:

```
    val result = ComposeUIViewController {
        compose stuff
    }
    paintBlack(result.view)
    platform.vc.navigationController?.pushViewController(result, animated = true)

…

private fun paintBlack(v: UIView) {
    v.backgroundColor = WC.dark_main        
    for (child in v.subviews) paintBlack(child)
}
```

But that didn't work at all. Version `1.5.10-beta01` does fix the white flash for me during the controller animation.

**Comment by chrisbanes** [comment]
1.5.10-beta02 has fixed the issue for us. I didn’t try beta01 though so not sure if that contains the fix.

**Comment by GuilhE** [comment]
1.5.10-beta01 and beta02 fixed for me

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3492">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
